### ISSUE TITLE
Sanitize displayId entries

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/libSBOLj#101]
The values put into displayId should be sanitized to ensure that they are not just strings, but strings that comply with the required naming format.

**Comment by cjmyers** [comment]
We have added this sanitizing function to the Version 1 to Version 2 converter because the old libSBOLj allowed people to create unsanitary displayIds, even though they were illegal.  However, the Version 2 reader throws exceptions on unsanitary displayIds, since these are invalid SBOL 2 and we don't allow them to be created.  Do you think we should sanitize them?  Hopefully, no library we develop will create them.

**Comment by jakebeal** [comment]
What do you do if a tool-writer lets a person write a bunch of arbitrary unicode junk in a field for entering displayIds, then passes that do a constructor?  If you can handle that case, I think we are good.

**Comment by cjmyers** [comment]
We throw an exception.  So a tool-writer using libSBOLj (and hopefully libSBOLc) will be unable to store them.  The only question is what to do if they generate a file using some other means with this junk, and we have to read it.  Since libSBOLj 1.0 did not prevent the user doing this, we decided to sanitize SBOL 1.0 displayIds automatically.  However, since the specification is clear and the library development is prepared for not allowing this, I think we want to be strict.  This will hopefully force the other tool writer not using our libraries to make their tool compliant.  Compliance testing I think is one of our next big priorities.
