### ISSUE TITLE
createCopy(TopLevel topLevel, String URIprefix, String displayId, String version) fail for persistentID

### ISSUE THREAD

**Issue by EGC1995** [SynBioDex/libSBOLj#188]
create copy not adding types to URIs.

**Comment by cjmyers** [comment]
This is perhaps not so simple.  The typical copy approach will inherit the types if it is part of the original.  The issue though is when you pass in the prefix, it will lose the types.  Therefore, the createCopy methods will need to somehow determine if the types are already present and add only if they not, otherwise you get two copies of the types which is also incorrect.

**Comment by cjmyers** [comment]
I cannot think of a clean way to deal with this, and furthermore automatic type insertion into the URI appears problematic and likely should be dropped, especially since we now allow URI prefix to be sent for create methods.
