### ISSUE TITLE
Add file extension for write methods writing to a file in SBOLWriter

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/libSBOLj#236]
It would be nice to automatically add filename extentions, i.e. ".rdf", ".json", and ".ttl" for write methods that write to a file. Also, if one provides any one of these extensions in the filename string, it should check against the file type specified by the user. If they do not match, then generates a warning, and append the correct file extension. If they match, then do not add the extension.

**Comment by cjmyers** [comment]
I'm not so sure about this one.  We don't really have a standard file extension.  In iBioSim, we use .sbol and we also allow .xml for import.  I don't think we can assume a file extension.

**Comment by zgzn** [comment]
For RDF/XML, the file extension is recommended by W3 to be ".rdf" on all platforms (http://www.w3.org/TR/REC-rdf-syntax/#section-MIME-Type). This is just for convenience for using the write method, as the users do not need to manually provide the file extension when they are asked to provide a file name. This also helps in case user provides no file extension or an incorrect one. For example, if they write "Foo.rfd" by mistake, then the correct file extension will still be given, although the output RDF/XML file name is "Foo.rfd.rdf".

It is up to the software tools that use the library to deal with the file extension, but providing a standard (or recommended) one is okay, I think. 

Also, when the original request was made, we supported writing of RDF/XML, Turtle, and JSON. Providing an extension makes it clear.

**Comment by cjmyers** [comment]
If we do this though, it will become impossible to write a file with any extension except “.rdf”, but in some instance we might want a different extension (such as .sbol, .xml).  I think it is up to the user of the library to decide what file extension they want to use for SBOL files.  I’m not sure of any way to default this without essentially compelling users to ALWAYS use “.rdf”.  Since this is only a recommended practice, I don’t think we should make it mandatory.

**Comment by zgzn** [comment]
OK. I see. The users of the library can have the freedom to choose their own file extensions. Luckily, our reader does not require a file extension and does not depend on the one provided.
