### ISSUE TITLE
SBOLDocument create methods + defaultURIPrefix

### ISSUE THREAD

**Issue by eoberortner** [SynBioDex/libSBOLj#300]
currently, the SBOLDocument provides create methods (to instantiate SBOL objects) which don't need a URI. However, when using such a create method, then the defaultURIPrefix is not set anywhere, i.e. it stays NULL. When serializing the SBOLDocument then an IllegalArgumentException ``URI prefix must not be null''  is thrown. 

Example:
SBOLDocument document = new SBOLDocument();
document.createSequence("displayID", "ACGT", org.sbolstandard.core2.Sequence.IUPAC_DNA);
SBOLWriter.write(document, file);

possible alternatives:
1) don't provide such methods
2) set the defaultURIPrefix member variable of the SBOLDocument (e.g. in the SBOLDocument's constructor)

**Comment by cjmyers** [comment]
The exception is actually thrown immediately when you call createSequence.  If you remove the write, you will see that.  Since this give you an error immediately, it should not be difficult to fix the code.  

I don’t think we should do option 1, as having a default URI prefix really allows code to become much simpler.  We are using these methods like crazy in our use of the library.  We basically never provide the prefix on create.

I don’t think we should do option 2, since some users may prefer to always pass the URI prefix and never use the default URI prefix and forcing them to provide one with the constructor may be objectionable.  I

I think the current approach is actually the correct one which is to tell the user of the library immediately when you have “mis-used” these helper methods.  I think if you are a user that prefers to use the default URI prefix (like us), this catches your error of not setting it quickly.  If you are a user that does not like to use these, you can catch the error that you forgot to provide the URI prefix quickly.

**Comment by eoberortner** [comment]
Sorry! my bad!

after looking more carefully into the stack-trace, the exception is actually thrown in the createSequence() method. 
and that’s fine!

Thanks,
Ernst

**Comment by eoberortner** [comment]
it’s just a little bit weird though… offering a method that throws an exception when you use it. 

anyway, if that’s the community’s decision, then I can live with it. :)

Thanks,
Ernst

**Comment by cjmyers** [comment]
Hi Ernst,

When began working on libSBOLj, we were told throwing exceptions was the proper way to do this in Java rather than returning NULL on errors.  We have recently changed all methods that throw validation exceptions to be “checked” which means the user should know that the exception is possible and be prompted to try/catch or mark the function as throws.  I think this is a good mechanism to prevent these types of error conditions being missed by developers.  

Sorry for the confusion.

Chris
