### ISSUE TITLE
JavaDoc for sortedComponents method in ComponentDefinition class

### ISSUE THREAD

**Issue by mehersam** [SynBioDex/libSBOLj#348]
Specify how the Components are being sorted. Mention how the sorting functionality works

**Comment by zgzn** [comment]
Updated method comments for getSortedComponents and getSortedSequenceAnnotations in ComponentDefinition. It would be nice to test these methods to validate the method comments. It is interesting to see how SAs in a ComponentDefinition instance are sorted if they each have different location type. For example, SA1 has a range, and SA2 has a cut and it is located within the range of SA1, and SA3 has a generic location which does not have a specific value of its location.

**Comment by cjmyers** [comment]
There are indeed some weird corner cases.  To say how things resolve, you need to look at the compareTo methods in each Location class.

In the example you give, SA1 would come before SA2, since the start is before the cut.  However, looking at the code, I’m not sure things are consistent about GenericLocations.  I thought I made it put them either all at the beginning or end, but I’m really not sure.

To be honest, I don’t think this function makes much sense when things are overlapping or unspecified.  For GenericLocation, one must use the sequenceConstraints for the sort. 

We definitely need several tests to see if this is at least doing something consistent.

Chris

**Comment by zgzn** [comment]
Tested SA sorting with several cases shown below.  Priority is given to a sequence annotation whose location has a lower (starting) value. Generic location always comes last. If a cut's value is the same as a range's starting value, it comes before the range. Two SAs with the exact same location are sorted with their display ID's lexicographical order. 

	public static void main(String[] args) throws SBOLValidationException {
		SBOLDocument doc = new SBOLDocument();
		doc.setDefaultURIprefix("http://sbols.org/");
		doc.setComplete(true);
		
		ComponentDefinition cd = doc.createComponentDefinition("cd1", ComponentDefinition.DNA);
		SequenceAnnotation sa_range1 = cd.createSequenceAnnotation("sa_range1", "range1", 4, 10);
		SequenceAnnotation sa_range2 = cd.createSequenceAnnotation("sa_range2", "range2", 3, 7);
		SequenceAnnotation sa_range3 = cd.createSequenceAnnotation("sa_range3", "range3", 3, 7);
		SequenceAnnotation sa_cut1 = cd.createSequenceAnnotation("sa_cut1", "cut1", 2);
		SequenceAnnotation sa_cut2 = cd.createSequenceAnnotation("sa_cut2", "cut2", 3);
		SequenceAnnotation sa_cut3 = cd.createSequenceAnnotation("sa_cut3", "cut3", 4);
		SequenceAnnotation sa_cut4 = cd.createSequenceAnnotation("sa_cut4", "cut4", 6);
		SequenceAnnotation sa_cut5 = cd.createSequenceAnnotation("sa_cut5", "cut5", 7);
		SequenceAnnotation sa_cut6 = cd.createSequenceAnnotation("sa_cut6", "cut6", 10);
		SequenceAnnotation sa_cut7 = cd.createSequenceAnnotation("sa_cut7", "cut7", 10);
		SequenceAnnotation sa_gl1 = cd.createSequenceAnnotation("sa_g1", "gl1");
		SequenceAnnotation sa_gl2 = cd.createSequenceAnnotation("sa_g2", "gl2");
		}
