### ISSUE TITLE
Infinite loop and fail to detect a cycle

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/libSBOLj#359]
I'm not quite sure what is happening here, but I can successfully reproduce this in SBOLDesigner (commit d1c091f727a818f521914617b4bc180cbaf3ff74).  

1. Open SBOLDesigner using default URIprefix and default rootComponent name
2. Drop in a generic promoter
3. Focus in (double click) on the promoter
4. Drop in another generic promoter.  This should show up as "Pro1".
5. Rename Pro1 to just Pro
6. A cycle isn't detected, even though Pro contains itself.
7. Focus out back to the root component, which causes an infinite loop in getImpliedNucleicAcidSequence() when SBOLDesigner tries to update the sequence since the sequence is recursively defined. 

This is quite an interesting bug!

**Comment by cjmyers** [comment]
Interesting indeed.  The question I have is what sequence of libSBOLj calls does this.  I’m guessing something like this:

1) SBOLDocument doc = new SBOLDocument();
    doc.setDefaultURIPrefix(“…”);
    ComponentDefinition root = doc.createComponentDefinition(“rootComponent”,…)
2) ComponentDefinition cd = doc.createComponentDefinition(“Pro”,…)
    root.createComponent(“Pro”,PUBLIC,”Pro”)
3) root = cd;
4) ComponentDefinition cd = doc.createComponentDefinition(“Pro1”,…)
    Component comp = root.createComponent(“Pro1”,PUBLIC,”Pro1”)
5) This is the fuzzy one for me.  When you change the displayId, do you change both the Component and CD that it points to?  If so, you should first be checking if the CD with that displayId already exists, and if so, not create it.  Instead, you would be editing this existing CD.  What would this even mean?  Would you strip its Components at this point, since that is part of what is the CD?  Also, for the Component, you would need to remove the existing one and replace it with a new one.  My guess is perhaps you are just changing the existing ones definition:
   comp.setDefinition(“Pro”,…).  Is this correct?

Ah, I see the problem now.  The method setDefinition(…) does not check for cycles!  Good catch.  We likely have several of these types of bugs.

Chris

**Comment by cjmyers** [comment]
This should be fixed now.

**Comment by michael13162** [comment]
I tested it and everything works like a charm.  Thanks!
