### ISSUE TITLE
nested objects that should be top-level throws exception in SBOLReader

### ISSUE THREAD

**Issue by drdozer** [SynBioDex/libSBOLj#390]
I have the xml:

```
<?xml version="1.0" ?><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:prov="https://www.w3.org/ns/prov#" xmlns:dc="http://purl.org/dc/terms/" xmlns:so="http://purl.obolibrary.org/obo/SO" xmlns:biopax="http://www.biopax.org/release/biopax-level3.owl#" xmlns:tutorial="http://shortbol.ico2s.org/tutorial/addingSequences/7#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:sbo="http://purl.obolibrary.org/obo/SBO" xmlns:chebi="http://purl.obolibrary.org/obo/CHEBI" xmlns:edam="http://edamontology.org/format" xmlns:sbol="http://sbols.org/v2#" xmlns:xsd="http://www.w3.org/2001/XMLSchema#" xmlns:stdlib="https://raw.githubusercontent.com/drdozer/shortbolCommunity/master/"><sbol:ComponentDefinition rdf:about="http://shortbol.ico2s.org/tutorial/addingSequences/7#pTetR"><sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#DnaRegion"></sbol:type><sbol:role rdf:resource="http://identifiers.org/so/SO:0000167"></sbol:role><sbol:sequence><sbol:Sequence rdf:about="http://shortbol.ico2s.org/tutorial/addingSequences/7#ncPMaK3y"><sbol:encoding rdf:resource="http://www.chem.qmul.ac.uk/iubmb/misc/naseq.html"></sbol:encoding><sbol:elements>tccctatcagtgatagagattgacatccctatcagtgatagagatactgagcac</sbol:elements></sbol:Sequence></sbol:sequence></sbol:ComponentDefinition></rdf:RDF>

```

When read with libSBOLj, I get this exception:

```
[info]                  java.lang.ClassCastException: uk.ac.ncl.intbio.core.datatree.NestedDocument$Impl cannot be cast to uk.ac.ncl.intbio.core.datatree.Literal
[info] -----------------------------------Results-----------------------------------
[info] 6                Failure('java.lang.ClassCastException: uk.ac.ncl.intbio.core.datatree.NestedDocument$Impl cannot be cast to uk.ac.ncl.intbio.core.datatree.Literal')
[info] Failures:
[info] uk.co.turingatemyhamster.shortbol.LibsboljTestSuite.tutorialExamples.addingSequences.6
[info]                  java.lang.ClassCastException: uk.ac.ncl.intbio.core.datatree.NestedDocument$Impl cannot be cast to uk.ac.ncl.intbio.core.datatree.Literal
[info] org.sbolstandard.core2.SBOLReader.parseComponentDefinitions(SBOLReader.java:1470)
[info] org.sbolstandard.core2.SBOLReader.readTopLevelDocs(SBOLReader.java:821)
[info] org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:522)
[info] org.sbolstandard.core2.SBOLDocument.read(SBOLDocument.java:2257)
[info] org.sbolstandard.core2.SBOLFactory.read(SBOLFactory.java:1471)
[info] 

The SBOL file is malformed, as there is a sequence object embedded inside the sequence property of the component definition. The libSBOLj reader seems to not consider this possibility, so fails. A warning or error message would be better I think, as this is the kind of mistake that is quite common when generating files manually or with home-brew tooling.

**Comment by cjmyers** [comment]
I think I can do one better.  In each place where a URI for a TopLevel object is expected, we can extract the object:

else if (namedProperty.getName().equals(Sbol2Terms.ComponentDefinition.hasSequence))
{
	if (namedProperty.getValue() instanceof Literal) {
		if (!(((Literal<QName>) namedProperty.getValue()).getValue() instanceof URI)) {
			throw new SBOLValidationException("sbol-10512", topLevel.getIdentity());
		}
		sequences.add(URI.create(((Literal<QName>) namedProperty.getValue()).getValue().toString()));
	}
	else if (namedProperty.getValue() instanceof IdentifiableDocument) {
		Sequence sequence = parseSequences(SBOLDoc,(IdentifiableDocument<QName>)namedProperty.getValue());
		sequences.add(sequence.getIdentity());
	}
}

This produces the following result on your example:

<?xml version="1.0" ?>
<rdf:RDF xmlns:prov="https://www.w3.org/ns/prov#" xmlns:sbo="http://purl.obolibrary.org/obo/SBO" xmlns:so="http://purl.obolibrary.org/obo/SO" xmlns:tutorial="http://shortbol.ico2s.org/tutorial/addingSequences/7#" xmlns:biopax="http://www.biopax.org/release/biopax-level3.owl#" xmlns:sbol="http://sbols.org/v2#" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:chebi="http://purl.obolibrary.org/obo/CHEBI" xmlns:stdlib="https://raw.githubusercontent.com/drdozer/shortbolCommunity/master/" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:xsd="http://www.w3.org/2001/XMLSchema#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:edam="http://edamontology.org/format">
  <sbol:ComponentDefinition rdf:about="http://shortbol.ico2s.org/tutorial/addingSequences/7#pTetR">
    <sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#DnaRegion"/>
    <sbol:role rdf:resource="http://identifiers.org/so/SO:0000167"/>
    <sbol:sequence rdf:resource="http://shortbol.ico2s.org/tutorial/addingSequences/7#ncPMaK3y"/>
  </sbol:ComponentDefinition>
  <sbol:Sequence rdf:about="http://shortbol.ico2s.org/tutorial/addingSequences/7#ncPMaK3y">
    <sbol:elements>tccctatcagtgatagagattgacatccctatcagtgatagagatactgagcac</sbol:elements>
    <sbol:encoding rdf:resource="http://www.chem.qmul.ac.uk/iubmb/misc/naseq.html"/>
  </sbol:Sequence>
</rdf:RDF>

**Comment by cjmyers** [comment]
I would still not make this the “standard” serialization, but we can accept as an alternative.

**Comment by cjmyers** [comment]
You have kind of uncovered a fairly significant problem.  We have many casts to Literal<QName> which are not checked.  We need to go back and add a instanceof check on each of these.  In most cases, this is simply an error.  If for example, you find a NestedDocument when a DisplayId String is expected, this is clearly incorrect.  In other cases, like the one you sent, a NestedDocument in a place where a URI is expected could be converted into a TopLevel object and the URI could be extracted from it.  

In either case, the amount of coding is about the same, so I guess we can go ahead and make this an alternative form.  

BTW: recently, we stumbled upon an SBOL1 file that had done this.  I don’t think this is common, since I’ve only found one SBOL1 file that has done this, but again supporting this form appears to be not too difficult.

**Comment by cjmyers** [comment]
This should be fixed in the latest snapshot.  Please test and close this issue, if you agree.

Namely, you should no longer get casting exceptions.  You will either get a proper SBOL validation exception OR in some cases it will allow inlined Top-Levels.  Namely, in the following situations:

1) A Sequence can be nested within a ComponentDefinition.
2) A Model can be nested within a ModuleDefinition.
3) A ComponentDefinition can be nested within a Component or FunctionalComponent.
4) A ModuleDefinition can be nested within a Module.
5) Any TopLevel can be nested within a Collection.

Finally, not that write still always pulls all Top-Levels to the top-level.

Chris
